// src/slic3r/GUI/RemoteAPI/RemoteAPIConfig.hpp
#pragma once

#include <string>

namespace Slic3r { namespace GUI { namespace RemoteAPI {

// Persisted in AppConfig (main-thread only: load()/save() must run on the GUI thread).
struct Config
{
    bool        enabled  { false };
    int         port     { 13130 };
    // Deliberately localhost-only. Remote control includes file loading, preset
    // mutation and slicing; cleartext LAN transport would expose the bearer token.
    bool        bind_lan { false };
    bool        notify   { true };  // toast in-app when the API changes state
    std::string token;

    static Config      load();
    void               save() const;
    // 32 hex characters generated by OpenSSL's CSPRNG.
    static std::string generate_token();
};

}}} // namespace

